#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
VERSION="$(python3 -c 'from prazycron import __version__; print(__version__)')"
echo "Checking PrazyCron $VERSION"
python3 -m unittest discover -s tests -v
python3 -m compileall -q prazycron
if command -v xvfb-run >/dev/null 2>&1; then
  xvfb-run -a python3 -m prazycron.main --gui --smoke-test
fi
if command -v desktop-file-validate >/dev/null 2>&1; then
  desktop-file-validate packaging/prazycron.desktop
fi
if command -v appstreamcli >/dev/null 2>&1; then
  appstreamcli validate --no-net packaging/net.prazynka.PrazyCron.metainfo.xml
fi
python3 - <<'PYICON'
from pathlib import Path
from PIL import Image
for path in sorted(Path('assets').glob('prazycron-*.png')):
    image=Image.open(path).convert('RGBA')
    low, high=image.getchannel('A').getextrema()
    if low != 255 or high != 255:
        raise SystemExit(f'Icon is not opaque: {path} alpha={low}..{high}')
print('Icon opacity: OK')
PYICON
if grep -RniE 'AI[- ]generated|generated by (AI|ChatGPT)|created with (AI|ChatGPT)|made with (AI|ChatGPT)' .   --exclude-dir=.git --exclude-dir=build --exclude-dir=dist --exclude='*.png'; then
  echo "Development-process attribution was found." >&2
  exit 1
fi
echo "Release checks passed."
